FROM pathwaycom/pathway:latest

# Set working directory inside the container
WORKDIR /app

# Copy everything from your current folder into the container’s /app folder
COPY . .

# Run your Python program
CMD ["python", "main.py"]
